name: Action test
on:
  #push:
  #  branches: [ "master" ]
  workflow_dispatch:
  #pull_request:
  #  branches: [ "master" ]
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Create file to upload
        run: |
            mkdir folder
            touch folder/test.txt
      - name: Minio upload
        uses: jansitarski/minio-copy-discord-notify@master
        with:
          endpoint: ${{ secrets.MINIO_ADDRESS }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: ${{ secrets.MINIO_BUCKET }}
          source_file: 'folder/test.txt'
          target_dir: '/'
          # Optional inputs with their defaults:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          webhook_title: "MinIO upload"
          webhook_desc: "Uploaded file to bucket"
